# Generated by Django 5.2.1 on 2025-06-12 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ds_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='ds_title', max_length=200)),
                ('priority', models.IntegerField(db_column='nr_priority', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('due_date', models.DateTimeField(auto_now=True, db_column='dt_modified', null=True)),
                ('done', models.BooleanField(db_column='is_done', default=False)),
                ('user', models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='ds_content')),
                ('priority', models.IntegerField(db_column='nr_priority', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created', null=True)),
                ('done', models.BooleanField(db_column='is_done', default=False)),
                ('task_list', models.ForeignKey(db_column='id_task_list', on_delete=django.db.models.deletion.CASCADE, to='tasktracking_app.tasklist')),
            ],
        ),
    ]
