# Generated by Django 5.2.3 on 2025-06-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasktracking_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='category',
            field=models.ForeignKey(db_column='id_category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasktracking_app.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, db_column='ds_content', null=True),
        ),
    ]
